### PR TITLE
Add inline validations

### PR DESCRIPTION
**Pull request by stevenpetryk**
This will validate the form as the user fills it out. Still a bit of a WIP as the code is a little messy.

### CODE REVIEW

**Comment by maxcell** [comment]
I know this is still a work in progress, but just a comment. We should probably be sure the preferred email is valid before freezing it or they cannot receive their information.
image

**Comment by maxcell** [comment]
Another thing that I am curious about. Why is it that on the actual form (once you got through `/apply`) you do not have the borders but on the home page you do? However amazing touch I think with making them informational pieces! I think this will definitely add quite a bit of value 😄 
on `/apply`
on `/`

**Comment by stevenpetryk** [comment]
These issues will be addressed in another PR, this was just for inline validation of the main form :blush:

Good to merge?

**Comment by maxcell** [comment]
Sorry I didn't back to this yeah :+1: I am happy with it!

**Comment by stevenpetryk** [comment]
whew sorry, was in the shower. think I'm gonna close this one out.

**Comment by maxcell** [comment]
What a time.

**Pull request closed without merging**
